spring:
  profiles:
    active:
      - DBDataSource
      - inMemoryDB
server:
  baseUrl: http://localhost:8080/
  imageUrl: images/
  imageServerDir : C:/images/lab07/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:1000/
---
spring:
  profiles: remote
server:
  baseUrl: http://localhost:8080/
  imageUrl: images/